let Name = prompt ('Яке Ваше ім\'я ?');
let SurName = prompt ('Яке Ваше прізвище ?');
let Number = +prompt ('Яке Ваше улюблене число?');
console.log ('Вітаю '+Name+" "+SurName+"! Ваше улюблене число - " + Number);
let YearofBirth = +prompt("В якому році Ви народились?");
var AGE = 2023- YearofBirth;
console.log ('Ваш вік - ' + AGE); 
var FirstNum = +prompt("Введіть перше число");
var SecondNum = +prompt("Введіть друге число");
console.log ("Сума чисел " + (FirstNum+SecondNum));
console.log ("Різниця чисел " + (FirstNum-SecondNum));
console.log ("Добуток чисел " + (FirstNum*SecondNum));
console.log ("Ділення чисел " + (FirstNum/SecondNum));
let Remainder1,Remainder2;
Remainder1= Math.trunc (FirstNum/SecondNum);
Remainder2= FirstNum - Remainder1*SecondNum;
console.log ("Остача від ділення числа "+FirstNum+" на число " + SecondNum + " рівна " + Remainder2);
let RandomNum = +prompt (" Введіть будь яке число ");
const Result= RandomNum % 2 ===0 ? "парне" : "парне ";
console.log (`Число ${RandomNum} є ${Result}`);
